services:
  ros2_web_bridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ptu_web_bridge
    restart: unless-stopped
    ports:
      - "8080:8080" # Interface Web
      - "9090:9090" # ROSBridge WebSocket
    volumes:
      - ./web:/app/web
    privileged: true
    # Substitua a porta abaixo pela porta real do seu ESP32 no WSL (ex: ttyUSB0 ou ttyACM0)
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
      - SERIAL_PORT=/dev/ttyUSB0